# Generated by Django 5.1.1 on 2024-09-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_featured_product_hot_product_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/hover/'),
        ),
    ]
